### ISSUE TITLE
Provide a project description for pypi

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/SurfaceTopography#102]
Currently on pypi, this is shown at https://pypi.org/project/SurfaceTopography/0.94.0/:
![grafik](https://user-images.githubusercontent.com/9113541/121503712-9cc65400-c9e1-11eb-9b6b-6bc9c9668680.png)

It would be more welcoming for new users if there is some description, a short example and a link to the documentation.

**Comment by pastewka** [comment]
I thought this was obtained from setuptools. `setup.py` passes a description to setuptools:
```python
description="Read and analyze surface topographies",
```
