### ISSUE TITLE
generic_fourier_derivative

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/SurfaceTopography#111]
currently `fourier_derivative` returns the two first order derivatives.

I suggest to refactor `fourier_derivative` -> `fourier_first_derivatives`

And implement a generalized version of the fourier derivatives: 

```python
def generic_fourier_derivative(topography, orderx=-1, ordery=0):
    nx, ny = topography.nb_grid_pts
    sx, sy = topography.physical_sizes

    qx = 2 * np.pi * np.fft.fftfreq(nx, sx / nx).reshape(-1, 1)
    qy = 2 * np.pi * np.fft.fftfreq(ny, sy / ny).reshape(1, -1)

    if nx % 2 == 0:
        qx[int(nx / 2), 0] = 0
    if ny % 2 == 0:
        qy[0, int(ny / 2)] = 0

    spectrum = np.fft.fft2(topography.heights())
    if orderx < 0:
        qx[qx==0] = 1
    if ordery < 0 :
        qy[qy==0] = 1

    spectrum *= (1j * qx) ** orderx * (1j * qy) ** ordery

    heights =np.fft.ifft2(spectrum)
    print(np.max(abs(heights.imag)))
    return heights.real
```

This actually also computes integrals. 

@pastewka what do you think ?

**Comment by pastewka** [comment]
Do we need the dedicated fourier derivative at all? You can just plug muFFT's Fourier derivative operator into `derivative`.

**Comment by AntoineSIMTEK** [comment]
Ah I didn't know that

**Comment by AntoineSIMTEK** [comment]
Do you have an example for the python interface ?

**Comment by pastewka** [comment]
Does this help? https://gitlab.com/muspectre/muspectre/-/blob/master/tests/libmufft/python_derivative_tests.py#L167
