### ISSUE TITLE
bicubic interpolation of 16384^2 surface on 32768 line throws segfault.

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/SurfaceTopography#142]
[minimal_example_segmentation_fault.zip](https://github.com/ContactEngineering/SurfaceTopography/files/7212744/minimal_example_segmentation_fault.zip)

I have attached a minimal example python file.

I am able to create the segfault on this grid size my 16GB RAM.

But also on a NEMO job with 128Gb ram (jobscript attached). 

Here are the outputs: 
```
nx: 256, n_cf: 128
generating topography
generating interpolator
interpolating without derivative
interpolating with first derivative
nx: 8192, n_cf: 16384
generating topography
generating interpolator
interpolating without derivative
interpolating with first derivative
nx: 16384, n_cf: 32768
generating topography
generating interpolator
interpolating without derivative
```
Here are the errors: 
```
/var/spool/torque/mom_priv/jobs/11349600.mg1.nemo.privat.SC: line 40:  3899 Segmentation fault      singularity exec --pwd $PWD -B $WS $WS/CrackFront.sif python3 segfault.py 16384 32768
```

**Comment by pastewka** [comment]
Sounds like an integer overflow, should be easy to fix.

**Comment by pastewka** [comment]
I just checked, we static cast everything nicely to `ptrdiff_t`, so there should be no integer overflows. Am investigating further.
