### ISSUE TITLE
XYZ-format for topographies (surface maps)

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/SurfaceTopography#158]
We currently do not support text-based XYZ input for topographies, i.e. files that simple list 3D-coordinates. The reason is that this in principle would allow completely unstructured data, e.g. point clouds, for which it is not clear what a surface representation would look like. However, we could support the following:

1. XYZ input for data where XY coordinates correspond to positions on an equally-distributed grid (simple, would require checking that these coordinates correspond to a grid)

2. XYZ input for data, where XY coordinates are slightly perturbed from an equally-distributed grid. Examples are the positions 
surface nodes of an FE calculation. This is more complicated since we currently do not support lateral displacement of the grid points. It would require some interpolation prescription (possibily linear) for ACF, PSD, etc. analysis.

Case 2. corresponds somewhat to our `NonuniformLineScans` - just for topography maps. Note that `NonuniformLineScans` support reentrant topographies but I don't see this for the full 3D case.

**Comment by mcrot** [comment]
On contact.engineering, I currently have 3 large datafiles (~150 MB each) which are in xyz-format.
The resulting shape is than sth like (3, 3874764), which is probably wrong. 
The calculating of contact mechanics (including DZI generation) for this takes hours, how can we deal with that?

**Comment by pastewka** [comment]
We should impose a limit to contact calculations. I suggest we limit it to max 32k per linear dimension and max 100e6 degrees of freedom. This allows 8k by 8k but not larger. The limits should be on the TopoBank end.

**Comment by mcrot** [comment]
Okay, I'll impose a limitation at TopoBank end, thanks.

**Comment by pastewka** [comment]
XYZ import has been implemented a while ago
