### ISSUE TITLE
Cannot read container with scipy netCDF

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/SurfaceTopography#185]
I downloaded the zip from https://contact.engineering/manager/surface/1039/

container = SurfaceTopography.read_container("surface.zip")
Exception ignored in: <function _SpecialNetCDFFile.close at 0x113d9c550>
Traceback (most recent call last):
  File "/Users/antoines/Documents/2103_webapp_paper/venv/lib/python3.8/site-packages/SurfaceTopography/IO/NC.py", line 58, in close
    self.flush()
  File "/Users/antoines/Documents/2103_webapp_paper/venv/lib/python3.8/site-packages/scipy/io/netcdf.py", line 404, in flush
    self._write()
  File "/Users/antoines/Documents/2103_webapp_paper/venv/lib/python3.8/site-packages/scipy/io/netcdf.py", line 408, in _write
    self.fp.seek(0)
ValueError: seek of closed file

installing netCDF4 solves the problem

**Comment by mcrot** [comment]
That's strange, why wasn't it installed? The requirements file has a line
```
netCDF4>=1.5.3
```
Or is it another package?

**Comment by AntoineSIMTEK** [comment]
If you just pip install SurfaceTopography, the requirements.txt will not be installed but not the install_requires. 

I think it was intended to remove netCDF4 from the mandatory dependencies.

Antoine SANNER (he/him)

**Comment by mcrot** [comment]
Ah, yes, right. Then we should mention this in the documentation. Currently it reads like `setup.py` and `requirements.txt` would have the same dependencies.

**Comment by pastewka** [comment]
Didn't we monkey patch scipy exactly because if this problem?

**Comment by pastewka** [comment]
We have dropped netCDF4 as a dependency altogether. This should work with latest version and a copy.
