### ISSUE TITLE
Checks do not run on pull requests

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/SurfaceTopography#194]

**Comment by AntoineSIMTEK** [comment]
@pastewka do you remember from the top of your head how the workflow files should look like ? They are a little different among the repositories

**Comment by AntoineSIMTEK** [comment]
There is the same problem on "Adhesion"

**Comment by pastewka** [comment]
@prs513rosewood solved this for https://github.com/libAtoms/matscipy here https://github.com/libAtoms/matscipy/pull/92 - I'll update the CI configuration accordingly.

**Comment by AntoineSIMTEK** [comment]
Thank you !
