### ISSUE TITLE
Mandatory requirements are never tested.

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/SurfaceTopography#202]
The test pipeline runs after installing requirements.txt

The consequence is that we do not know which requirements are actually mandatory for basic functionality of the code. 

I suggest that we either make all the requirements mandator via install_requires or create an additional pipeline that runs the 

I find that having optional requirements is a bit dangerous because the errors show up at runtime and it is sometimes difficult to attribute the error to a wrong package version. 

However, I understand that always installing all requirements is dangerous as well because it can create sometimes unnecessary version conflicts.

This issue applies to ContactMechanics and Adhesion as well.

**Comment by pastewka** [comment]
This has all been changed with the Meson build system. The only optional requirements are the ones used for testing.
