### ISSUE TITLE
Unsuccessful installation on MAC : Installation from source directory

### ISSUE THREAD

**Issue by sitangshugk95** [ContactEngineering/SurfaceTopography#219]
I am trying to install from source directory after having cloned the repository, as per the steps mentioned in https://contactengineering.github.io/SurfaceTopography/installation.html#direct-installation-with-pip . 
It is being able to install all dependencies except muFFT (screenshot attached) : 
<img width="501" alt="Screen Shot 2022-08-11 at 11 04 47 AM" src="https://user-images.githubusercontent.com/108830413/184178727-8e41d566-a6e4-4327-b0d1-909b5b0553bf.png">

How can I solve this issue?

**Comment by pastewka** [comment]
Related to #279

**Comment by pastewka** [comment]
Hi @sitangshugk95 - I have in recent months worked on macOS support and everything should now pip install nicely on Macs.
