### ISSUE TITLE
easy installation

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/SurfaceTopography#223]
After making the installation of muFFT easy.

If we allow to deactivate functionalities like the bicubic interpolation (needing linking to Lapack). 

Would we be able to install on windows ?

**Comment by pastewka** [comment]
I am currently working on muFFT wheels which now has PocketFFT build on and therefore no remaining external dependency. Once done, I will replace LAPACK with Eigen3 which should get rid of the external dependency for SurfaceTopography as well. We can then also build wheels here. Windows builds will hinge on whether I get those fire muFFT done.

**Comment by sannant** [comment]
Nice !

**Comment by pastewka** [comment]
This should be closed with #270
