### ISSUE TITLE
NonuniformLineScan cannot fulfill test_periodic_flag

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/SurfaceTopography#230]
`NonuniformLineScan` always returns
https://github.com/ContactEngineering/SurfaceTopography/blob/34816d954c4886440ba10eadda4a4b8b721526f3/SurfaceTopography/NonuniformLineScan.py#L91-L95
on the `is_periodic` flag and a reader returning such an object on the `topography` method can never fulfill
https://github.com/ContactEngineering/SurfaceTopography/blob/34816d954c4886440ba10eadda4a4b8b721526f3/test/IO/test_io.py#L382-L392

Is that intended?

**Comment by mcrot** [comment]
This looks strange. So the test always fails?

**Comment by pastewka** [comment]
This is bogus. It should not be possible to just overide the periodic flag. For *most* readers.

**Comment by pastewka** [comment]
The readers just pass through the periodic flag. I think this is not what we want. We could think about a pipeline function to modify the periodicity, but the reader itself should only allow specifying properties that are not in the file. Basically all readers for experimental instruments yield nonperiodic data.

**Comment by pastewka** [comment]
Changing this would a behavioral (API) change of the whole system.

@mcrot - How does TopoBank deal with periodicity?

**Comment by jotelha** [comment]
The question on whether the `topography` method should or should not allow overriding the periodic flag left aside, why should a `NonuniformLineScan` not allow periodicity per se? I can certainly imagine reading some periodic (likely computer-generated) profile on a non-uniform grid.

**Comment by pastewka** [comment]
That is right, but we currently do not support this

**Comment by pastewka** [comment]
This would require the `NonuniformTopography` to store additional information on the length of the scan. Right now it is identical to the distance between leftmost and rightmost data point. I'd be happy to add this, but not without a use-case.

**Comment by mcrot** [comment]
> Changing this would a behavioral (API) change of the whole system.
> 
> @mcrot - How does TopoBank deal with periodicity?

When uploading a topography, the user sees this checkbox:
![grafik](https://user-images.githubusercontent.com/9113541/196652910-0f3af0d3-babe-4c67-b904-a091f5c39f79.png)

So for only for 2D measurements and if no sizes are given in the original file, the user can decide to consider
a measurement as periodic. In other cases, the checkbox cannot be enabled.
Additionally, only detrend_mode "center" can be used if periodicity is enabled.

So the default is to store `False` for the `is_periodic` flag of a measurement, but in some cases it can be set to True by the user.
This flag is then used every time, when an instance of a `SurfaceTopography` topography is generated.
During analyses, `SurfaceTopography` makes use of it, not Topobank.

**Comment by pastewka** [comment]
Would it be a problem if we restricted it?

**Comment by jotelha** [comment]
For https://github.com/ContactEngineering/SurfaceTopography/pull/226 that means, I undo the modifications on NonUniformLineScan introduced in https://github.com/ContactEngineering/SurfaceTopography/pull/226/commits/6984072e8a9173f7020abb79ddfa6bbdfe330855 and simply remove `test_periodic_flag`  from the tests, alright?

**Comment by pastewka** [comment]
I'll push my changes in a second

**Comment by jotelha** [comment]
Issue handled by https://github.com/ContactEngineering/SurfaceTopography/commit/e5e5a70fc491794f4f177ec9655da3eb0e57cb16

If at some point a use case for periodicity in the NonuniformLineScan arises, begin with reintroducing the modifications undone by https://github.com/ContactEngineering/SurfaceTopography/commit/e6adaa300d2ea7b9580e4e115746d51947b1f066 and https://github.com/ContactEngineering/SurfaceTopography/commit/b6361e5db8091b2f3afa58628b3082fdd63e8c1e
