### ISSUE TITLE
Position and physical size conventions

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/SurfaceTopography#235]
With the `UniformLineScan`, x positions always start at zero, 
https://github.com/ContactEngineering/SurfaceTopography/blob/7c193a8ff41208006d3e5e0adbae4d0dbcf7a45a/SurfaceTopography/UniformLineScanAndTopography.py#L131-L147,
no matter what's the convention of the input.

In some file formats, positions don't start at zero, but at the first grid point.
In the Mitutoyo mock example, positions start at 0.5 um and run in 0.5 um steps up to 480 um, amounting to 960 data points in total. 

Currently, the reader determines the physical size
https://github.com/ContactEngineering/SurfaceTopography/blob/7c193a8ff41208006d3e5e0adbae4d0dbcf7a45a/SurfaceTopography/IO/Mitutoyo.py#L130
as the difference between first and last position to 479.5 um.

This, however, results in an erroneous distribution of 960 positions beginning at 0 and ending at ~ 479.0005 um, with a 479.5 / 960 ~ 0.4995 um step.

Hence, https://github.com/ContactEngineering/SurfaceTopography/commit/a1ed5d52a497f1da781cec6d64be85facf7359b4 sets physical size to the upper bound 480 um and disregards the lower bound 0.5 um to reproduce a position distribution with correct spacing.

This, however, contradicts the practice in `NonUniformLineScan`, https://github.com/ContactEngineering/SurfaceTopography/blob/7c193a8ff41208006d3e5e0adbae4d0dbcf7a45a/SurfaceTopography/NonuniformLineScan.py#L87-L89, which will report 479.5 um.

Readers should be able to produce `UniformLineScan` and `NonUniformLineScan` with same physical size and  coinciding positions when fed input data that coincide. Currently, there is the choice of either having physical size off, or positions off.

**Comment by jotelha** [comment]
https://github.com/ContactEngineering/SurfaceTopography/pull/236 resolves the position distribution issue.

**Comment by pastewka** [comment]
Are you suggesting to allow uniform line scans that don't start at 0? I am not sure if this is a good idea, it will break all kinds of upstream codes that currently assume this. Also, I don't see the advantage.

Maybe let's discuss this offline at some point.

**Comment by jotelha** [comment]
No, I guess should not change that, let me modify that my last sentence from above a little,

Readers should be able to produce UniformLineScan and NonUniformLineScan with same physical size and coinciding **relative** positions (grid spacing) wherever input data that coincides. Currently, there is the choice of either having physical size off, or *grid spacing* off.

**Comment by pastewka** [comment]
This boils down to a different interpretation of the data: Nonuniform line scans have data defined on a point, uniform have data defined on a "pixel" or "voxel". This leads to a difference of one grid spacing in the physical sizes of those topographies with identical data.

**Comment by jotelha** [comment]
Then having the physical size off by one grid spacing in otherwise equivalent UniformLinescan and NonuniformLinescan instances is the desired behavior, and I close this one.
