### ISSUE TITLE
Reliability cutoff depends on the unit of the topography

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/SurfaceTopography#275]
Attached is a minimal notebook demonstrating this bug.

@pastewka this is a big issue. Do you have an idea where this can come from and who should look at it ? 
[unit_issue_with_nans_and_sampling.html.zip](https://github.com/ContactEngineering/SurfaceTopography/files/10384266/unit_issue_with_nans_and_sampling.html.zip)

**Comment by pastewka** [comment]
I'll check what is going on. This sounds critical.

**Comment by pastewka** [comment]
This is a numerical issue. It goes away if I increase the tolerance of `brentq` here: https://github.com/ContactEngineering/SurfaceTopography/blob/c7dbaab13608748394054fdf9da1176c6cbfbbd2/SurfaceTopography/Generic/ScanningProbe.py#L88 ...but this makes things slower

**Comment by pastewka** [comment]
We should normalize by bandwidth
