### ISSUE TITLE
Units not working on .al3d files

### ISSUE THREAD

**Issue by jacekolender** [ContactEngineering/SurfaceTopography#276]
Wehn uploading a surface scan in the alicona format al3d, the unit field in step 3 of creating a twin is greyed out. But since it's a mandatory field, the twin cannot be ultimately created and no further operation can be done.

**Comment by pastewka** [comment]
The file was not included in the list of example files. The generic tests never ran, but they catch this error.

**Comment by pastewka** [comment]
PR #277 fixes this issue.

**Comment by jacekolender** [comment]
I have now successfully uploaded an al3d file, but the unit multiplier is set permanently to 1, so I get results that are off by rows of magnitude. As per example on the image attached, I got Rq roughness of 331 microns, where realistically I would not expect above 3 microns. Unless I'm doing something wrong with the analysis... 
![c-eng](https://user-images.githubusercontent.com/81159611/222710714-4ef8e219-5d64-4f2f-be08-0eacda8b013b.JPG)

**Comment by pastewka** [comment]
This looks like there is still a bug. Will look into this.

**Comment by pastewka** [comment]
Can you comment on the Sq value? Is that correct? It looks like the reader is assuming the wrong byte order when reading the file, but the overall height should be okay.

**Comment by jacekolender** [comment]
I think the Sq value of 0.3 mm (300 um) is quite probable.

**Comment by pastewka** [comment]
Okay, then the problem is just the data layout. I'll push and update soon(ish) - will let you know once that has happened.

**Comment by jacekolender** [comment]
Great!

**Comment by pastewka** [comment]
@jacekolender I've just updated the site, including a bug fix to the reader. Can you check whether the problem is resolved?

**Comment by jacekolender** [comment]
Hi, I'm terribly sorry I could not get back to this on time back in April. It caught me during a job change (and move across continents) and only now I had time to look into this and get back to this data. There is still issue with scaling. Software reads the scale between X-Y units and Z units as 1, when it's not. So I'm getting Rq and Sq results in mm instead of um. It's not a massive problem, I can manually scale it down. The other thing is that I get an error when exporting power spectrum to csv/txt.

**Comment by jacekolender** [comment]
PS. Happy to send you my file for testing if you would like to.
