### ISSUE TITLE
Unable to run example file locally even after successful installation of SurfaceTopography on Ubuntu

### ISSUE THREAD

**Issue by sitangshugk95** [ContactEngineering/SurfaceTopography#293]
I have been running the codes using docker images so far, but I am looking to be able to run them locally as a long-term solution.

I did `pip install SurfaceTopography` and it looks like it installed all required dependencies without any issues:
![Screenshot from 2023-02-13 16-12-47](https://user-images.githubusercontent.com/108830413/218586664-be3c0c15-e9fb-4679-ba0a-2f3877034184.png)

Then I just use `anaconda-navigator` , open Jupyter Notebook and try to run an example file "fourier_synthesis". However, I ma getting the following error:
![Screenshot from 2023-02-13 16-19-37](https://user-images.githubusercontent.com/108830413/218587749-d3c64f5c-6135-4f7f-a776-9839b56b7376.png)

Is this the correct way to run it? I remember when I use docker images to run, it shows "SurfaceTopography" as the ipy kernel on the top right side in Notebook, instead of "Python 3 (ipykernel)". Any help would be much appreciated. @jotelha @sannant @mcrot @pastewka

**Comment by sannant** [comment]
I am not familiar with this error, but I advice you to install a good editor like PyCharm or VStudio and on a linux machine and then to install the development stack there.

PyCharm should take care automatically . If you encounter issues, also have a look at 

https://contactengineering.github.io/SurfaceTopography/installation.html#installation-from-source-directory and below

**Comment by pastewka** [comment]
Is this on Ubuntu? This sounds like our wheel is incompatible with your bumpy version, but I have no idea how that happened. You can always try to force compilation with the --no-binary option, but you probably need to specify that option for both muSpectre and SurfaceTopography

**Comment by sannant** [comment]
Ah it might be that the docker container has too old versions of dependencies including muSpectre preinstalled. We would need to upload a fresh docker image.

**Comment by sannant** [comment]
But as I said, since Sitangshu is digging into the code, it is better that he develops it on an editor on an Ubuntu machine.

**Comment by sitangshugk95** [comment]
@sannant 

I got these done:

1.  Installed VStudio (also have Spyder/Jupyterlab and several other editors available on Anaconda.
2. Run `pip install SurfaceTopography` on the terminal of a **Linux system (Ubuntu)** 

I am still unable to run any file (shows the same error) locally. Since I am debugging/changing/writing my own code, it is very important that I am able to run it locally instead of resorting to docker images. Would you be willing to help me over a zoom/teams call sometime, when convenient?

**Comment by sitangshugk95** [comment]
> Is this on Ubuntu? This sounds like our wheel is incompatible with your bumpy version, but I have no idea how that happened. You can always try to force compilation with the --no-binary option, but you probably need to specify that option for both muSpectre and SurfaceTopography

Yes, this is on ubuntu.

I have installed only Surface Topography using `pip install SurfaceTopography` . I have not installed muSpectre or any other dependencies myself as I thought the current code already takes care of all dependencies. 

Where do I need to use the --no-binary option? Is it after installing SurfaceTopography while compiling the code? pip install SurfaceTopography --no-binary shows the following:
![Screenshot from 2023-03-06 22-53-18](https://user-images.githubusercontent.com/108830413/223324123-bb6d325d-8624-4dcd-995c-001d7545634e.png)

**Comment by pastewka** [comment]
You need to specify the package name again after the —no-binary flag, i.e. use ˋ—no-binary SurfaceTopographyˋ

**Comment by pastewka** [comment]
Okay, fantastic!
