### ISSUE TITLE
variance_half_derivative does not handle rolloff properly and is redundant anyway.

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/SurfaceTopography#314]
https://github.com/ContactEngineering/SurfaceTopography/blob/bf00a09dc2c58b6db7dd8d076830f6e4530001b8/SurfaceTopography/Models/SelfAffine.py#LL218C19-L218C19

returns negative values when short_wavelength cutoff is smaller than rolloff wavelength. 

This is better implemented in variance_derivative anyway

**Comment by pastewka** [comment]
Didn't we get rid of this code @sannant ?

**Comment by sannant** [comment]
Yes in commit #0c541987 , sorry for letting the issue open
