### ISSUE TITLE
Unable to read published containers

### ISSUE THREAD

**Issue by sitangshugk95** [ContactEngineering/SurfaceTopography#330]
I am trying to run an [Adhesion example file](https://github.com/ContactEngineering/Adhesion/blob/master/docs/examples/adhesive_simulation_rough.py) locally, but I get an error "File is not a zip file": 
![Screenshot from 2023-09-26 19-59-13](https://github.com/ContactEngineering/SurfaceTopography/assets/108830413/65f439e3-1fa7-4b66-ad59-909373279511)
 It seems like it is encountering this in a file IO.py in SurfaceTopography (hence, I am posting here instead of Adhesion), but I don't seem to be able to find that file in the current version. I am opening this after a long time - have there been any changes that might be causing this issue?

**Comment by pastewka** [comment]
This is because we changed the contact.engineering API, newer versions of `SurfaceTopography` are able to access the latest API.
