### ISSUE TITLE
NC files cannot be read from binary streams

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/SurfaceTopography#49]
```python
from SurfaceTopography import Topography
import numpy as np
Topography(np.array([[1,2,], [3,4]]), (1,1), periodic=True).to_netcdf("test_netcdf.nc")
read_topography("test_netcdf.nc", mode='rb')
```
results in 
```
~/miniconda3/envs/topobank/lib/python3.7/site-packages/SurfaceTopography/IO/__init__.py in read_topography(fn, format, communicator, **kwargs)
    237     """
    238     with open_topography(fn, format=format,
--> 239                          communicator=communicator) as reader:
    240         t = reader.topography(**kwargs)
    241     return t

~/miniconda3/envs/topobank/lib/python3.7/site-packages/SurfaceTopography/IO/__init__.py in open_topography(fobj, format, communicator)
    185                     # has to be set back to the top of the file
    186                     fobj.seek(0)
--> 187         raise CannotDetectFileFormat(msg)
    188     else:
    189         if format not in lookup_reader_by_format.keys():

[...]

tried NCReader: 
 [Errno 2] No such file or directory: b"<_io.BufferedReader name='test_netcdf.nc'>"
```
First, we should list an NC file in the test setup for binary streams: https://github.com/ComputationalMechanics/SurfaceTopography/blob/b03e71f102f9a09a8211289bf6ddc3c73f249778/test/IO/test_io.py#L100

**Comment by pastewka** [comment]
This will never work, because the NetCDF library does not hook not into how Python handles streams. It opens a file from the file system verbatim. The only way to get this to work is by dumping everything into a temporary file and then passing that to the NetCDF library.

**Comment by mcrot** [comment]
Thanks - okay, too bad. I'm not sure how to handle this yet, I need to do some experiments.

**Comment by pastewka** [comment]
If this is needed, we could implement it on the SurfaceTopography side.

**Comment by AntoineSIMTEK** [comment]
Ok, if not, we should remove nc from the supported fileformats.

**Comment by pastewka** [comment]
I'd vote for dumping this into a temporary file and then opening it. This should be fully transparent and handled on the SurfaceTopography side.

**Comment by pastewka** [comment]
No need to revive this ourselves, see here: https://github.com/pacificclimate/pupynere-pdp

**Comment by pastewka** [comment]
From discussion @mcrot and @AntoineSIMTEK: We would like to use NetCDF for normalized storage in the S3 in TopoBank (as sort of an intermediate cache): This means, we need fast NetCDF support, i.e. direct reading from streams.

**Comment by pastewka** [comment]
Scipy has pupynere build in: https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.netcdf_file.html (I had forgotten about that)

**Comment by pastewka** [comment]
Hi @mcrot, I switched to the `scipy` reader. This should be able to read from a screen, *but* it closes the stream when done. Would that work for TopoBank?

**Comment by mcrot** [comment]
Thanks for switching. I'll check and let you know.

**Comment by mcrot** [comment]
I've tried in Topobank and the format detection returned:

```
tried NCReader: 
 hasattr(): attribute name must be string
```

I get the same error, when I open the file in the console from a binary stream:
```python
In [3]: import SurfaceTopography

In [4]: SurfaceTopography.__version__
Out[4]: '0.92.1.dev95+g9d667b2c'

In [5]: r = open_topography('../data/linear/linear_2d_topography.nc')

In [6]: t = r.topography()

In [7]: t
Out[7]: <SurfaceTopography.UniformLineScanAndTopography.Topography at 0x7f566e241f40>

In [8]: t.physical_sizes
Out[8]: (5, 10)

In [10]: r = open_topography(open('../data/linear/linear_2d_topography.nc', mode='rb'))
---------------------------------------------------------------------------
CannotDetectFileFormat                    Traceback (most recent call last)
<ipython-input-10-6f8624999def> in <module>
----> 1 r = open_topography(open('../data/linear/linear_2d_topography.nc', mode='rb'))

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/__init__.py in open_topography(fobj, format, communicator)
    188                     # has to be set back to the top of the file
    189                     fobj.seek(0)
--> 190         raise CannotDetectFileFormat(msg)
    191     else:
    192         if format not in lookup_reader_by_format.keys():

[...]

tried NCReader: 
 hasattr(): attribute name must be string

[...]
```
It seems there is still a problem with binary streams..

Scipy itself works:
```python
In [11]: from scipy.io import netcdf

In [13]: nc_file = netcdf.netcdf_file('../data/linear/linear_2d_topography.nc')

In [14]: nc_file.dimensions
Out[14]: OrderedDict([('x', 5), ('y', 10)])

In [15]: nc_file = netcdf.netcdf_file(open('../data/linear/linear_2d_topography.nc', mode='rb'))

In [16]: nc_file.dimensions
Out[16]: OrderedDict([('x', 5), ('y', 10)])
```

**Comment by mcrot** [comment]
I'll have a look at this..

**Comment by mcrot** [comment]
I've added a small nc file to the list of binary example files and some errors came up. 
The error with `hasattr` can be easily fixed, but there is a problem with the closed stream during
detection:

```
                finally:
                    if hasattr(fobj, 'seek'):
                        # if the reader crashes the cursor in the file-like object
                        # has to be set back to the top of the file
>                       fobj.seek(0)
E                       ValueError: seek of closed file
```
Would it be a problem to reopen the stream after using `netcdf_file` if it was open before and closed afterwards?
It's a workaround, but should be okay, I think.

**Comment by pastewka** [comment]
Is reopening possible? You need to know where the stream came from to do that, correct?

**Comment by pastewka** [comment]
As an alternative, we could monkey-patch scopy.io.netcdf

**Comment by mcrot** [comment]
Oh no, you're right, reopening seems to be impossible.
Yes, monkey-patching is an option. Or maybe a subclass of `netcdf_file` with changed behaviour.
I'll try that tomorrow.

**Comment by mcrot** [comment]
Hm, I've fixed another problem (rewinding the stream after our own check of magic bytes), but one issue remains:
The stream is still closed. There is already a `scipy` issue for that: https://github.com/scipy/scipy/issues/13905

It seems like the closing happens on garbage collection. I'll try to use the workaround with the subclass in our code.

**Comment by pastewka** [comment]
I think the stream closes when the descructor of netcdf_file is called.
This may happen upon Garbage collection. I am not sure if that behavior
can be changed by subclassing, I think you will need to monkey patch
the destructor (if that is possible).

Am Montag, dem 26.04.2021 um 03:42 -0700 schrieb Michael Röttger:

**Comment by mcrot** [comment]
I confirm that with #84 , now Topobank can read NC files written by package `SurfaceTopography`.
