### ISSUE TITLE
Fourier_systhesis fails in 1D odd number of grid points

### ISSUE THREAD

**Issue by sindhu2993** [ContactEngineering/SurfaceTopography#56]

**Comment by pastewka** [comment]
I cannot reproduce this.

@AntoineSIMTEK - do you know what was going on here?

**Comment by AntoineSIMTEK** [comment]
![grafik](https://user-images.githubusercontent.com/40853209/141251143-c85a5e98-b99a-4af5-9eae-4445643e3cce.png)

I think __you__ fixed it at the beginning of september.... 

I had a quick look at the tests and I think all are using even numbers of grid points. 

Can you add tests (e.g. via parametrize) for odd nb. grid points. 

Also happy to do it.

**Comment by pastewka** [comment]
Have already added those tests...
