### ISSUE TITLE
Implement 'save' method for detrended topographies

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/SurfaceTopography#61]
Currently `.save()` cannot be used for detrended topographies:

```python
import numpy as np
from SurfaceTopography import Topography
info = dict(unit='nm')
y = np.arange(10).reshape((1, -1))
x = np.arange(5).reshape((-1, 1))
arr = -2 * y + 0 * x
t = Topography(arr, (5,10), info=info)
t.save("topo.txt")  # works
t.detrend('center').save("topo.txt")  # -->  exception: AttributeError: Unkown attribute 'save' and no analysis or pipeline function of this name registered 
```

Workaround: First apply `.squeeze()`, then `.save()` is available.

The question is also, which other methods are missing on detrended topographies.
Maybe we can make up a list of expected methods and arguments and loop over this list in a test?!

**Comment by pastewka** [comment]
We should implement `save` as a pipeline function, then it will automatically become available for the detrended topographies
