### ISSUE TITLE
API cleanup: 1D vs 2D versions of analysis functions

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/SurfaceTopography#63]
The API is inconsistent: `rms_height` has an argument that allows us to tell it whether to do the 1D or 2D calculations, `rms_slope` and `rms_curvature` do not support 1D anaylsis at all. For `autocorrelation` and `power_spectrum` there are explicit 1D and 2D versions.

I prefer explicit functions for 1D and 2D analysis, i.e.
* `rms_height_1D`, `rms_height_2D`, `rms_slope_1D`, ... like it's done for `autocorrelation` etc.
* I am not sure whether the `_1D` and `_2D` suffix is good, since a `_1D` analysis can also be executed on a topography map.

Any thoughts @AntoineSIMTEK @mcrot

**Comment by mcrot** [comment]
I've just had a look at the autocorrelation functions and I think the suffixes `_1D` and `_2D` make it quite clear what it is about.
Normally I would expect that the function name describes the result and not the type of input argument, so `_1D` for
maps and line scans is okay for me. Maybe we can add an additional sentence to the docstring e.g.

```python
def SurfaceTopography.Uniform.Autocorrelation.autocorrelation_1D(topography, direction=0):
"""Compute the one-dimensional height-difference autocorrelation function (ACF).

The 1D ACF can be computed on both, 2D maps and line scans, see first argument `topography`.
[...]
```
Another idea: We could also use the direction parameter for 2D, e.g. if it is `None`. But I like the `_2D` suffix more.

Concerning the `rms_height` function with the extra parameter: I haven't found it in the documentation.
It is not the `kind` parameter, is it?

**Comment by pastewka** [comment]
I meant the `kind` parameter. Setting it to `"Sq"` gives a 2D analysis, setting to `"Rq"` a 1D analysis. This is super confusing. I will switch throughout to a `_1D` and `_2D` suffix scheme.

**Comment by AntoineSIMTEK** [comment]
Yes I think rms_height_1D with a mention in the doc that this is "Rq" is fine.

**Comment by mcrot** [comment]
During the discussion about the webapp paper, Tevis mentioned that we may use "area" and "line" instead of "2D" and "1D",
because the data for an area can be regarded as 2D (x,y) or 3D (x,y,z). Does this also apply for this issue?

**Comment by pastewka** [comment]
After discussion with @mcrot and @AntoineSIMTEK: `rms_height_from_profile`, `rms_height_from_area`, `rms_slope_from_profile`, `rms_gradient`, `rms_curvature_from_profile`, `rms_curvature_from_area` - `rms_gradient` has a clearly distinct name because there is a factor of sqrt(2) between the quantity obtained from profile or area.

Same for `autocorrelation_from_profile` and `autocorrelation_from_area` etc.
