### ISSUE TITLE
Documentation up to date for v0.93?

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/SurfaceTopography#86]
With version v0.93, the API changed, see e.g. #63 .
In the introduction for the [online docs](https://contactengineering.github.io/SurfaceTopography/usage.html?highlight=rms_height) for this version, there is an example with `topo.rms_height()`. Is this still up-to-date?

Given a non-uniform topography, this method still exists:
https://contactengineering.github.io/SurfaceTopography/source/SurfaceTopography.Nonuniform.html?highlight=rms_height#SurfaceTopography.Nonuniform.ScalarParameters.rms_height

**Comment by pastewka** [comment]
No, this is no longer up to date. We need to fix this.
