### ISSUE TITLE
File format examples use > 200 MB

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/SurfaceTopography#88]
We currently have lots of file format examples in the repository. I do think we need those for testing purposes and there will likely be more than those in the future.

1. We could simply ignore and accept that these files need to be in the repository.
2. We could move them to a separate (non-version controlled) location and download during testing.
3. We could try to find smaller example files or reduce the number of grid points. (We can only do this for files that we can actually write).

Any suggestions/thoughts?

**Comment by AntoineSIMTEK** [comment]
Where is the size of the repository causing problems ? 
a. Are there limitations on github ? 
b. Or is it the time for installation ?

For b the most elegant would be an option to exclude directories on pypi.
I speculate that exists for the installation but not for the download. 

Solution 2. would then be the simplest alternative. I suggest to put the files in a public github repository in ContactEngineering. We just need to clone it to obtain the test files.

**Comment by pastewka** [comment]
Github has a 10 GB limit I think. As long as we don't hit that we are good.

PyPI is much smaller but I think we are already excluding the file format examples for that.

**Comment by mcrot** [comment]
Hm, solution 2 adds more complexity. We will have to make always ensure that the file repo and the code repo are in sync. One problem is, that we could have different branches on the code side, but only one file repo.
I think this might cause problems in the future. Also we cannot run the tests without being online.
And if we're online, it will always take time and bandwidth to download the files on every test run. 
Probably this will get on our nerves..

I prefer solution 3: I think having small files in the repo is no problem. 
We should make the simplest example files possible. This also can help for other tests (analysis?) and speeds up testing.
If this is not possible, we should ask people with access to instruments to provide as small sample files.

**Comment by pastewka** [comment]
For solution 3 we need to ask people with access to the instruments for small files.

**Comment by pastewka** [comment]
We could pull file format examples from surfaces published at https://contact.engineering/ - is there an automated way to do that, @mcrot

**Comment by mcrot** [comment]
Yes, e.g.:
```python
import requests
import io
from SurfaceTopography.Container import read_container

def read_published_container(publication_url):
    # First get the page for the publication in order
    # to get the download URL
    publication_response = requests.get(publication_url)
    download_url = publication_response.url + "download/"

    # Then download and read container
    container_response = requests.get(download_url)
    container_file = io.BytesIO(container_response.content)
    return read_container(container_file)
```

This currently works for containers with binary data files, e.g.:
```python
read_published_container("https://contact.engineering/go/btpax/")
```

This currently doesn't work if a text file is included in the container, e.g.:
```python
In [86]: read_published_container("https://contact.engineering/go/25t52/")
/home/michael/work/imtek/SurfaceTopography/SurfaceTopography/Container/IO.py:70: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  meta = yaml.load(z.open('meta.yml'))
---------------------------------------------------------------------------
CannotDetectFileFormat                    Traceback (most recent call last)
<ipython-input-86-a71139bcb657> in <module>
----> 1 read_published_container("https://contact.engineering/go/25t52/")

~/work/imtek/SurfaceTopography/pull_surface_container.py in read_published_container(publication_url)
     17     # return container_file
     18 
---> 19     return read_container(container_file)
     20 
     21 

~/work/imtek/SurfaceTopography/SurfaceTopography/Container/IO.py in read_container(fn, datafile_keys)
     84                 if datafile_key is None:
     85                     raise ValueError('Could not detect data file.')
---> 86                 t = read_topography(
     87                     z.open(datafiles[datafile_key]),
     88                     physical_sizes=physical_sizes,

~/work/imtek/SurfaceTopography/SurfaceTopography/IO/__init__.py in read_topography(fn, format, communicator, **kwargs)
    240         The object containing the actual topography data.
    241     """
--> 242     with open_topography(fn, format=format,
    243                          communicator=communicator) as reader:
    244         t = reader.topography(**kwargs)

~/work/imtek/SurfaceTopography/SurfaceTopography/IO/__init__.py in open_topography(fobj, format, communicator)
    189                     # has to be set back to the top of the file
    190                     fobj.seek(0)
--> 191         raise CannotDetectFileFormat(msg)
    192     else:
    193         if format not in lookup_reader_by_format.keys():

CannotDetectFileFormat: tried XYZReader: 
 Expected two or three columns for topography that is a list of positions and heights.

tried AscReader: 
 cannot use a string pattern on a bytes-like object
[...]
```

**Comment by pastewka** [comment]
Nice... can we stick this function into `SurfaceTopography`?

**Comment by mcrot** [comment]
Yes, of course .. looks already similar to `read_container`. We should add tests with both, binary and text data files.
I can add it.
