### ISSUE TITLE
Dropping Python 3.6 support

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/SurfaceTopography#89]
Python 3.6 does not support seek on files opened in a `ZipFile`. This was introduced in Python 3.7.

See here: https://bugs.python.org/issue22908

We need this if we want to be able to read NetCDF files stored in a ZIP container.

Do we need to continue supporting Python 3.6? Ubuntu 20.04 LTS has Python 3.8 but 18.04 LTS has 3.6.

Any thoughts @mcrot @AntoineSIMTEK

**Comment by pastewka** [comment]
See also https://github.com/ContactEngineering/SurfaceTopography/pull/79

**Comment by AntoineSIMTEK** [comment]
I am fine with dropping 3.6. 

I had issues installing muFFT on a singularity machine with ubuntu 20, but as soon as this is fixed I will upgrade it. 
I guess one can still apt install a specific python version.

**Comment by mcrot** [comment]
Me too, dropping 3.6 is fine. The production machine is still on Ubuntu 18.04 LTS, but the web app run on a container
with own interpreter.

**Comment by pastewka** [comment]
Okay, will drop this then.
