### ISSUE TITLE
Simple xyz format is not detected?

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/SurfaceTopography#93]
When uploading a measurement in contact.engineering, the help text states there is an input format for
"plain text (x,y,z coordinates)":
> SurfaceTopography information can be provided as coordinate data. This is a text file that contains either two columns (for line scans) or three columns (for two-dimensional topographies) of data. The parser does not support reading header information. Units can therefore not be provided directly within this file format.
>
>Line scans can be provided on a non-uniform grid. The x-coordinates do not need to be equally spaced and the surface specified in this format can be reentrant. The code interprets such topographies as piecewise linear between the points that are specified in the file.
>
>Two-dimensional topography maps need to reside on a regular grid. The x- and y-coordinates need to be equally spaced.

When loading this simple text file
```
0 0 1
0 1 1
0 2 1
0 3 1
1 0 1
1 1 2
1 2 2
1 3 1
2 0 1
2 1 1
2 2 1
2 3 1
3 0 1
3 1 1
3 2 1
3 3 1
```
I would expect as result a 2D topography on a 4x4 map, the format should be `xyz`. Instead the format is
`asc` and the points are interpreted as a map with 3 columns and 16 rows:
```python
In [17]: r=open_topography('simple_xyz.txt')

In [18]: r.format()
Out[18]: 'asc'

In [19]: r.topography()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-3113e5da337a> in <module>
----> 1 r.topography()

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/FromFile.py in topography(self, channel_index, physical_sizes, height_scale_factor, info, periodic, subdomain_locations, nb_subdomain_grid_pts)
    122                 raise RuntimeError('Reader supports only a single channel 0.')
    123 
--> 124             physical_sizes = self._check_physical_sizes(physical_sizes, self._topography.physical_sizes)
    125 
    126             # Rewind to position where the data is. Otherwise this method

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/Reader.py in _check_physical_sizes(self, physical_sizes_from_arg, physical_sizes)
    302         if physical_sizes is None:
    303             if physical_sizes_from_arg is None:
--> 304                 raise ValueError("`physical_sizes` could not be extracted from file, you must provide it.")
    305         else:
    306             if physical_sizes_from_arg is None:

ValueError: `physical_sizes` could not be extracted from file, you must provide it.

In [20]: r.topography(physical_sizes=(1,1))
Out[20]: <SurfaceTopography.UniformLineScanAndTopography.Topography at 0x7f52aca91dc0>

In [21]: t=r.topography(physical_sizes=(1,1))

In [22]: t.heights()
Out[22]: 
array([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.],
       [0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.],
       [1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1.]])
```

Should the file be formatted in a different way? Then this should be mentioned in the help text.
Or is this a bug of the format detection?

This is probably also the cause for https://github.com/ContactEngineering/TopoBank/issues/585.

**Comment by AntoineSIMTEK** [comment]
isn't xyz = asc ? 
In the test of surface topography, read_xyz reads a two column asc file

**Comment by mcrot** [comment]
No these are two different functions:
https://github.com/ContactEngineering/SurfaceTopography/blob/6487a85d7bb8ce162edecc50a99e17241ad368e1/SurfaceTopography/IO/Text.py#L64
https://github.com/ContactEngineering/SurfaceTopography/blob/6487a85d7bb8ce162edecc50a99e17241ad368e1/SurfaceTopography/IO/Text.py#L285

**Comment by AntoineSIMTEK** [comment]
I think the problem is that both readers can successfully read this data. And read_asc is called before

**Comment by mcrot** [comment]
So this can be probably be fixed by trying the `xyz` reader first?

**Comment by AntoineSIMTEK** [comment]
Yes I saw that. It seems that we call asc text files in matrix format and xyz text files in xy or xyz format

**Comment by AntoineSIMTEK** [comment]
Yes I agree.  If we ignore the edgecase where someone uploads a 3x3 topography in matrix format. 
And I think we can ignore it.

**Comment by mcrot** [comment]
Yes we could ignore that case I think.

Are you sure the file extension is taken into account? 
Renaming doesn't seem not work. I've renamed by example above to `simple_xyz.xyz` and it's still format `asc`.

**Comment by AntoineSIMTEK** [comment]
nono it doesn't take the extension into account. I just mean this confuses me.

**Comment by mcrot** [comment]
:smile: misunderstood. Okay, I'm preparing a PR for this issue and also rename the test file.

**Comment by mcrot** [comment]
Maybe we should invent some special comment in the header which proposes a file format, e.g.:
```
format: xyz
```
In the case of our colleague, he could circumvent the auto detection and upload his file nevertheless.

**Comment by mcrot** [comment]
Alternative: Topobank could have a dropdown which allows to preselect the format and not to to autodetection.

**Comment by mcrot** [comment]
Hm .. the file cannot be loaded with format specification either:
```python
In [41]: r=open_topography('simple_xyz.xyz', format='xyz')
/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/Text.py:333: RuntimeWarning: divide by zero encountered in true_divide
  binx = np.array(x / dx + 0.5, dtype=int)
/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/Text.py:333: RuntimeWarning: invalid value encountered in true_divide
  binx = np.array(x / dx + 0.5, dtype=int)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-71c4282f24b3> in <module>
----> 1 r=open_topography('simple_xyz.xyz', format='xyz')

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/__init__.py in open_topography(fobj, format, communicator)
    194                 "{} not in registered file formats {}".format(
    195                     fobj, lookup_reader_by_format.keys()))
--> 196         return lookup_reader_by_format[format](fobj, **kwargs)
    197 
    198 

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/FromFile.py in __init__(self, fobj)
     92             if hasattr(fobj, 'tell'):
     93                 self._file_position = fobj.tell()
---> 94             self._topography = reader_func(fobj)
     95             if CHANNEL_NAME_INFO_KEY in self._topography.info:
     96                 self._channel_name = self._topography.info[CHANNEL_NAME_INFO_KEY]

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/common.py in func_wrapper(fobj, *args, **kwargs)
    109 
    110         try:
--> 111             retvals = func(fobj_text, *args, **kwargs)
    112         finally:
    113             if is_binary_stream(fobj):

~/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/IO/Text.py in read_xyz(fobj, physical_sizes, height_scale_factor, info, periodic, tol)
    332         dx = x[1] - x[0]
    333         binx = np.array(x / dx + 0.5, dtype=int)
--> 334         n = np.bincount(binx)
    335         ny = n[0]
    336         assert np.all(n == ny)  # FIXME: Turn assert into exception

<__array_function__ internals> in bincount(*args, **kwargs)

ValueError: 'list' argument must have no negative elements
```
This should be solved together with the original issue..

**Comment by AntoineSIMTEK** [comment]
It seems that it doesn't allow for roundoff errors in the pixel positions

**Comment by mcrot** [comment]
Ah okay - another thing is that it assumed the data is sorted such that the first column (x) varies before the second (y).
Otherwise
```python
dx = x[1] - x[0]
```
would be zero, also on regular grids. This order is not the case in my test file. So we should order first maybe .. if this is feasible on large files.
